### ISSUE TITLE
Increase char count from 600 to 2000

### ISSUE THREAD

**Issue by Sighvatur** [PaysonAB/PaysonPayments-PHP#2]
Using this SDK there is a validation on all merchant fields, the limit is set to 600 chars in the validation but the REST api can handle about  2000 chars.
Increasing this to match the REST api's max would be beneficial for systems generating checkoutUri's that are longer than 600 chars.

https://github.com/PaysonAB/PaysonPayments-PHP/blob/269333522019e7daa3a4af2120ad9393ee7ff84a/src/Validation/ValidateCreateCheckoutData.php#L55

**Comment by Sighvatur** [comment]
Issue fixed by these two commits:
https://github.com/PaysonAB/PaysonPayments-PHP/commit/74d432d74bf897a9e119fb55f39221baf3f90867
https://github.com/PaysonAB/PaysonPayments-PHP/commit/d67dde0c840acb4afea2b049032e903f3b38b980

**Comment by PaysonSDK** [comment]
Resolved.
